TensorFlow Libraby

1. Classification example


In [ ]:
# load_data
import tensorflow as tf 
mnist = tf.keras.datasets.mnist 
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [40]:
X_train.shape

(60000, 28, 28)

In [41]:
y_train.shape

(60000,)

In [42]:
# preprocessing
X_train, X_test = X_train/255.0, X_test/255.0 

In [43]:
# build_neural_network
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Input, Flatten, Dense, Dropout 

model = Sequential()
model.add(Input((28,28))) # 1 instance 28,28 pixels
model.add(Flatten()) #make 1D
model.add(Dense(128, activation="relu")) #neurons and break linerity
model.add(Dense(64, activation="relu")) 
model.add(Dropout(0.2)) #regularization/overfitting fix
model.add(Dense(10)) #output


In [44]:
nonsense_prediction = model(X_train[:1]).numpy() #model's prediction
nonsense_prediction

array([[ 0.3905958 , -0.1766607 ,  0.11348175, -0.3732096 , -0.44106302,
        -0.33633932, -0.06252632,  0.18447636, -0.21200584, -0.56732   ]],
      dtype=float32)

In [45]:
tf.nn.softmax(nonsense_prediction).numpy() #probability of prediction

array([[0.16420075, 0.0931148 , 0.12445894, 0.07649951, 0.07148094,
        0.07937271, 0.10437266, 0.13361605, 0.08988113, 0.06300247]],
      dtype=float32)

In [ ]:

from tensorflow.keras.losses import SparseCategoricalCrossentropy
loss_fn = SparseCategoricalCrossentropy(from_logits=True) #model's losses , wrongness
# -tf.math.log(1/10)
loss_fn(y_train[:1], nonsense_prediction)


<tf.Tensor: shape=(), dtype=float32, numpy=2.5336008071899414>

In [47]:
from tensorflow.keras.optimizers import Adam 
optimizer = Adam(learning_rate=0.01) #optimizer: update models for improve

# compile model
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])


In [48]:
# train model
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9131 - loss: 0.3096
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9393 - loss: 0.2259
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9448 - loss: 0.2082
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9496 - loss: 0.1991
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9537 - loss: 0.1880
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9546 - loss: 0.1805
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9562 - loss: 0.1791
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9583 - loss: 0.1687
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9592 - loss: 0.1709
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9614 - loss: 0.1641


In [49]:
# evaluate model
model.evaluate(X_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.9577 - loss: 0.2896


[0.2896171510219574, 0.9577000141143799]

In [ ]:
tf.argmax(tf.nn.softmax(model(X_test[:1])).numpy(), axis=1)  #return the highest probabity index

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([7], dtype=int64)>

In [51]:
y_test[:1]

array([7], dtype=uint8)

2. Regression exp

In [30]:
import pandas as pd 
df = pd.read_csv("housing.csv")
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [52]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 

X, y = df.drop(columns=["MedHouseVal"], axis=1), df["MedHouseVal"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [53]:
X_train_scaled.shape

(16512, 8)

In [55]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Input, Dense

model = Sequential([
    Input((8,)),
    Dense(64, activation="relu"),
    Dense(64, activation="relu"),
    Dense(1)
])

model.compile(optimizer="adam", loss="mse", metrics=["mae","r2_score"])


In [56]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 735us/step - loss: 0.7775 - mae: 0.5747 - r2_score: 0.4153
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - loss: 0.4351 - mae: 0.4499 - r2_score: 0.6728
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 0.3705 - mae: 0.4307 - r2_score: 0.7214
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - loss: 0.3527 - mae: 0.4184 - r2_score: 0.7348
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 0.3407 - mae: 0.4114 - r2_score: 0.7438
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 0.3422 - mae: 0.4063 - r2_score: 0.7427
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 0.3356 - mae: 0.3979 - r2_score: 0.7476
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 0.3333 - mae: 0.3922 - r2_score: 0.7493
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - loss: 0.3060 - mae: 0.3840 - r2_score: 0.7699
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - loss: 0.3014 - mae: 0.380

In [57]:
model.evaluate(X_test_scaled,y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - loss: 0.3127 - mae: 0.3863 - r2_score: 0.7663


[0.31266680359840393, 0.3862755000591278, 0.76633220911026]

In [58]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64